logging:
  level:
    ru:
      talismanandco:
        jobhelpercore: ERROR

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

talismanov:
  vacancies:
    hh:
      base-url: https://api.hh.ru/vacancies
  courses:
    epam:
      #переписать на относительный путь или класспас
      file-path: src/main/resources/learn_epam_courses.html
      base-url: https://learn.epam.com