insert into vacancy (title, company, salary_from, salary_to, currency, gross, create_date)
values ('Java developer', 'Google', 3500, 5000, 'USD', false, CURRENT_TIMESTAMP);
insert into vacancy (title, company, salary_from, salary_to, currency, gross, create_date)
values ('Python developer', 'Yandex', 75000, 140000, 'RUB', true, CURRENT_TIMESTAMP);
insert into vacancy (title, company, salary_from, salary_to, currency, gross, create_date)
values ('Javascript developer', 'Facebook', 3000, 5000, 'USD', false, CURRENT_TIMESTAMP);

insert into skill(name)
values ('css'),
       ('aop'),
       ('springdata'),
       ('servlet'),
       ('quarkus'),
       ('okd'),
       ('micronaut'),
       ('kiss'),
       ('ajax'),
       ('plsql'),
       ('lambda'),
       ('java'),
       ('mvvm'),
       ('xml'),
       ('jpa'),
       ('orm'),
       ('devops'),
       ('c#'),
       ('app'),
       ('solid'),
       ('javascript'),
       ('grpc'),
       ('nosql'),
       ('postgresql'),
       ('node'),
       ('regex'),
       ('groovy'),
       ('sdk'),
       ('rxjava'),
       ('restful'),
       ('jsp'),
       ('lucene'),
       ('hibernate'),
       ('jmeter'),
       ('logback'),
       ('selenium'),
       ('typescript'),
       ('ejb'),
       ('postgres'),
       ('haskell'),
       ('pgplsql'),
       ('rdbms'),
       ('c'),
       ('svn'),
       ('concurrency'),
       ('gradle'),
       ('teamwork'),
       ('elastic'),
       ('kubernetes'),
       ('confluence'),
       ('scss'),
       ('bitbucket'),
       ('spring'),
       ('oop'),
       ('postgre'),
       ('generics'),
       ('webdriver'),
       ('mysql'),
       ('multithreading'),
       ('agile'),
       ('swift'),
       ('jvm'),
       ('patterns'),
       ('retrofit2'),
       ('collection'),
       ('thymeleaf'),
       ('ide'),
       ('lombok'),
       ('reactive'),
       ('shell'),
       ('http'),
       ('scrum'),
       ('mongo'),
       ('polymer'),
       ('golang'),
       ('android'),
       ('оrм'),
       ('jdbc'),
       ('istio'),
       ('docker'),
       ('solr'),
       ('linux'),
       ('json'),
       ('log4j'),
       ('junit'),
       ('go'),
       ('sphinx'),
       ('redmine'),
       ('awk'),
       ('aws'),
       ('tomcat'),
       ('react'),
       ('youtrack'),
       ('redis'),
       ('elasticsearch'),
       ('collections'),
       ('kanban'),
       ('spatial'),
       ('azure'),
       ('python'),
       ('expressjs'),
       ('angular'),
       ('kafka'),
       ('jdbs'),
       ('artifactory'),
       ('algorithms'),
       ('clojure'),
       ('openshift'),
       ('js'),
       ('springboot'),
       ('workfusion'),
       ('glassfish'),
       ('stream'),
       ('jenkins'),
       ('portlet'),
       ('rabbitmq'),
       ('php'),
       ('gwt'),
       ('cucumber'),
       ('restfull'),
       ('networking'),
       ('jmm'),
       ('swagger'),
       ('liquibase'),
       ('cloud'),
       ('jms'),
       ('j2ee'),
       ('e2e'),
       ('html'),
       ('javacore'),
       ('net'),
       ('jira'),
       ('postgis'),
       ('maven'),
       ('dry'),
       ('gitlab'),
       ('soap'),
       ('unix'),
       ('scala'),
       ('mybatis'),
       ('webflux'),
       ('mockito'),
       ('jquery'),
       ('sql'),
       ('rust'),
       ('security'),
       ('git'),
       ('mvc'),
       ('mongodb'),
       ('rest'),
       ('kotlin'),
       ('quartz'),
       ('wicket'),
       ('mariadb'),
       ('tdd'),
       ('ioc'),
       ('frontend'),
       ('django'),
       ('fastapi'),
       ('asyncio'),
       ('gcc'),
       ('solidity'),
       ('posix'),
       ('html5'),
       ('c++'),
       ('ruby'),
       ('windows'),
       ('macos'),
       ('ios'),
       ('kamatera'),
       ('oracle'),
       ('amazon web'),
       ('google cloud'),
       ('shopify'),
       ('woocommerce'),
       ('bigcommerce'),
       ('magento'),
       ('opencart'),
       ('cloud security'),
       ('malware analysis'),
       ('ceh'),
       ('oscp'),
       ('olap'),
       ('tableau'),
       ('github'),
       ('springmvc'),
       ('jsf'),
       ('jboss'),
       ('jetty'),
       ('websphere'),
       ('weblogic'),
       ('hadoop'),
       ('sqlalchemy'),
       ('flask'),
       ('bash'),
       ('winapi'),
       ('buildroot'),
       ('ethernet'),
       ('сbuilder');

insert into vacancy_skill(vacancy_id, skill_id)
values (1, 1),
       (1, 4),
       (1, 5),
       (1, 8),
       (2, 2),
       (2, 4),
       (2, 8),
       (3, 3),
       (3, 4),
       (3, 8);
